#include <string>
#include <map>

#include "tag.h"

using std::map;
using std::string;

extern const map<string, Tag> KEYWORD_STR2TAG = {
	{"int",Tag::kw_int},
	{"void",Tag::kw_void},
	{"if",Tag::kw_if},
	{"else",Tag::kw_else},
	{"while",Tag::kw_while},
	{"return",Tag::kw_return},
};

extern const map<string, Tag> STR2TAG = {
	{"epsilon"			,Tag::epsilon},
	{"the_end"			,Tag::the_end},
	{"id"				,Tag::id},
	{"num"				,Tag::num},
	{"+"				,Tag::sb_add},
	{"-"				,Tag::sb_sub},
	{"*"				,Tag::sb_time},
	{"/"				,Tag::sb_divide},
	{"="				,Tag::sb_assign},
	{"=="				,Tag::sb_equal},
	{">"				,Tag::sb_g},
	{">="				,Tag::sb_ge},
	{"<"				,Tag::sb_l},
	{"<="				,Tag::sb_le},
	{"!="				,Tag::sb_ne},
	{";"				,Tag::sb_board},
	{","				,Tag::sb_separator},
	{"("				,Tag::sb_llb},
	{")"				,Tag::sb_rlb},
	{"{"				,Tag::sb_lbb},
	{"}"				,Tag::sb_rbb},
	{"int"				,Tag::kw_int},
	{"void"				,Tag::kw_void},
	{"if"				,Tag::kw_if},
	{"else"				,Tag::kw_else},
	{"while"			,Tag::kw_while},
	{"return"			,Tag::kw_return},

	{"program"			,Tag::program},
	{"dec_list"			,Tag::dec_list},
	{"dec"				,Tag::dec},
	{"dec_type"			,Tag::dec_type},
	{"func_dec"			,Tag::func_dec},
	{"var_dec"			,Tag::var_dec},
	{"params"			,Tag::params},
	{"stat_block"		,Tag::stat_block},
	{"param_list"		,Tag::param_list},
	{"param"			,Tag::param},
	{"pre_param"		,Tag::pre_param},
	{"in_dec"			,Tag::in_dec},
	{"stat_str"			,Tag::stat_str},
	{"in_var_dec"		,Tag::in_var_dec},
	{"pre_in_var_dec"	,Tag::pre_in_var_dec},
	{"stat"				,Tag::stat},
	{"if_stat"			,Tag::if_stat},
	{"while_stat"		,Tag::while_stat},
	{"return_stat"		,Tag::return_stat},
	{"assign_stat"		,Tag::assign_stat},
	{"expr"				,Tag::expr},
	{"add_expr"			,Tag::add_expr},
	{"comp_add_expr"	,Tag::comp_add_expr},
	{"comp_operator"	,Tag::comp_operator},
	{"term"				,Tag::term},
	{"pre_term"			,Tag::pre_term},
	{"factor"			,Tag::factor},
	{"pre_factor"		,Tag::pre_factor},
	{"func_type"		,Tag::func_type},
	{"call"				,Tag::call},
	{"argus"			,Tag::argus},
	{"argu_list"		,Tag::argu_list},
	{"pre_expr"			,Tag::pre_expr},
};

#ifdef DEBUG
extern const map<Tag, string> TAG2STR = {
	{Tag::epsilon		,"epsilon"},
	{Tag::the_end		,"the_end"},
	{Tag::id			,"id"},
	{Tag::num			,"num"},
	{Tag::sb_add		,"+"},
	{Tag::sb_sub		,"-"},
	{Tag::sb_time		,"*"},
	{Tag::sb_divide		,"/"},
	{Tag::sb_assign		,"="},
	{Tag::sb_equal		,"=="},
	{Tag::sb_g			,">"},
	{Tag::sb_ge			,">="},
	{Tag::sb_l			,"<"},
	{Tag::sb_le			,"<="},
	{Tag::sb_ne			,"!="},
	{Tag::sb_board		,";"},
	{Tag::sb_separator	,","},
	{Tag::sb_llb		,"("},
	{Tag::sb_rlb		,")"},
	{Tag::sb_lbb		,"{"},
	{Tag::sb_rbb		,"}"},
	{Tag::kw_int		,"int"},
	{Tag::kw_void		,"void"},
	{Tag::kw_if			,"if"},
	{Tag::kw_else		,"else"},
	{Tag::kw_while		,"while"},
	{Tag::kw_return		,"return"},

	{Tag::S0            ,"S0"},
	{Tag::program		,"program"},
	{Tag::dec_list		,"dec_list"},
	{Tag::dec			,"dec"},
	{Tag::dec_type		,"dec_type"},
	{Tag::func_dec		,"func_dec"},
	{Tag::var_dec		,"var_dec"},
	{Tag::params		,"params"},
	{Tag::stat_block	,"stat_block"},
	{Tag::param_list	,"param_list"},
	{Tag::param			,"param"},
	{Tag::pre_param		,"pre_param"},
	{Tag::in_dec		,"in_dec"},
	{Tag::stat_str		,"stat_str"},
	{Tag::in_var_dec	,"in_var_dec"},
	{Tag::pre_in_var_dec,"pre_in_var_dec"},
	{Tag::stat			,"stat"},
	{Tag::if_stat		,"if_stat"},
	{Tag::while_stat	,"while_stat"},
	{Tag::return_stat	,"return_stat"},
	{Tag::assign_stat	,"assign_stat"},
	{Tag::expr			,"expr"},
	{Tag::add_expr		,"add_expr"},
	{Tag::comp_add_expr	,"comp_add_expr"},
	{Tag::comp_operator	,"comp_operator"},
	{Tag::term			,"term"},
	{Tag::pre_term		,"pre_term"},
	{Tag::factor		,"factor"},
	{Tag::pre_factor	,"pre_factor"},
	{Tag::func_type		,"func_type"},
	{Tag::call			,"call"},
	{Tag::argus			,"argus"},
	{Tag::argu_list		,"argu_list"},
	{Tag::pre_expr		,"pre_expr"},
};
#endif // DEBUG
